export const GET_TODOS_REQUEST = 'CREATE_TODO_REQUEST'
export const GET_TODOS_SUCCESS = 'CREATE_TODO_SUCCESS'

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'

export const CREATE_TODO_REQUEST = 'GET_TODOS_REQUEST'

export const CLEAR_TODOS = 'CLEAR_TODOS'
