export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_ERROR = 'GET_USER_ERROR'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'

export const CLEAR_USER = 'CLEAR_USER'
